### ISSUE TITLE
Azure regions not up to date - Embedding widgets from Azure Video Analyzer

### ISSUE THREAD

**Issue by luisamiranda** [Azure-Samples/media-services-video-indexer#33]
I have been trying to use the @azure/video-analyzer-for-media-widgets npm package to render the insights widget in a Web UI, but it hasn't been working. 

After a long debugging session, This was the problem. Our AVAM is in westus region, but the npm package hasn't been updated to allow that region yet, and is not logging errors to the console correctly, but instead replacing invalid values with the default of "trial" it seems. This was the error when we found it.

```
'[{
  "keyword":"enum",
  "dataPath":"/location",
  "schemaPath":"#/properties/location/enum",
  "params":{"allowedValues":[
    "australiaeast",
    "centralindia",
    "eastasia",
    "eastus",
    "eastus2",
    "japaneast",
    "northeurope",
    "southcentralus",
    "southeastasia",
    "switzerlandnorth",
    "switzerlandwest",
    "trial",
    "uksouth",
    "westeurope",
    "westus2"
  ]},
  "message":"should be equal to one of the allowed values"
}]'
```

Here's where we found it:
![edge-debug-image](https://user-images.githubusercontent.com/22548484/142514524-313e25ff-0a12-49b0-a5e4-ebe572b99354.png)

The widget package itself doesn't seem to be open source; otherwise, I would make a pull request or at least post this there.

**Comment by nofaredanoren** [comment]
Hey

The problem is now solved and we've updated all regions. Thanks for reaching out!

Nofar
