### ISSUE TITLE
Video Player Widget - Error during new ARM get 

### ISSUE THREAD

**Issue by MACEL94** [Azure-Samples/media-services-video-indexer#34]
https://github.com/Azure-Samples/media-services-video-indexer/blob/a4c9324774d630aec2b85a48872344080e81df26/ApiUsage/ArmBased/Program.cs#L145

I believe this line is wrong, a different access token needs to be obtained with scope video and permission reader to be able to get the video player.

**Comment by tshoham** [comment]
The issue is fixed. You are right, the access token scope needs to be 'video'. The permission can be both 'contributor' or 'reader'.
Thanks for the heads up
