### ISSUE TITLE
Link to Contributing.md in Readme is Broken

### ISSUE THREAD

**Issue by MACEL94** [Azure-Samples/media-services-video-indexer#36]
There is no contributing.md file in this repo, or i didn't see it.
The link in the readme that we get when landing on this repo, points to nothing: 
https://github.com/Azure-Samples/media-services-video-indexer#contributing --> https://github.com/Azure-Samples/media-services-video-indexer/blob/master/CONTRIBUTING.md

**Comment by MACEL94** [comment]
the same is true for the license part https://github.com/Azure-Samples/media-services-video-indexer#license --> https://github.com/Azure-Samples/media-services-video-indexer/blob/master/LICENSE.md

**Comment by MACEL94** [comment]
> the same is true for the license part https://github.com/Azure-Samples/media-services-video-indexer#license --> https://github.com/Azure-Samples/media-services-video-indexer/blob/master/LICENSE.md

fixed in #37

**Comment by MACEL94** [comment]
@tshaiman let me know if I can help in any way

**Comment by tshaiman** [comment]
@MACEL94  Im not sure what needs to be added here , will consult our PM team . @Itnorman
