### ISSUE TITLE
problem with video name max length

### ISSUE THREAD

**Issue by thdotnet** [Azure-Samples/media-services-video-indexer#4]
Hi,

I'm facing a problem related to Video Indexer v2 connector on Logic Apps. It seems that it's limiting the video name length to around 40 chars however blobs allow up to 256 chars for a blob name (or maybe even more). Is there a way to update / fix this limitation?

**Comment by IngridAtMicrosoft** [comment]
Hi thdotnet. I will send your question to the engineering team.

**Comment by ika-microsoft** [comment]
Hi @thdotnet,

Video Indexer API limit the file name to 80 characters not 40. Can you provide more info on how you hit a 40 character limit?
Regarding increasing the 80 character limit. The limitation is not coming from the blob. 
I would like to suggest you raise this ask in our [user voice](https://cognitive.uservoice.com/forums/598144-video-indexer)

**Comment by IngridAtMicrosoft** [comment]
#please-close
