### ISSUE TITLE
LiveStreamAnalysis project link is broken

### ISSUE THREAD

**Issue by Erry91** [Azure-Samples/media-services-video-indexer#66]
Is this project still present? The link seems to be broken both in this Github repo and on the MS blog post [https://azure.microsoft.com/it-it/blog/live-stream-analysis-using-video-indexer/](https://azure.microsoft.com/it-it/blog/live-stream-analysis-using-video-indexer/)

**Comment by tshaiman** [comment]
@Erry91  we have removed this sample in both places , as we don't own the code that was contributed.
