### ISSUE TITLE
How to make sure uploadeVideo is only indexed once?

### ISSUE THREAD

**Issue by leolorenzoluis** [Azure-Samples/media-services-video-indexer#90]
What's the unique identifier to set so it knows that it doesn't have to index new videos with identical filename/content?

**Comment by tshaiman** [comment]
@leolorenzoluis : we have released a version this week that looks at the content Hash MD5 if such header exists on the Video URL provided. for example when you upload from Azure Blob Storage SaS or Google Storage or S3 , you have the content annotated with such Hash header. if you do not use those providers we take the URL + Param list as the "hash" string
